version: '3.7'

services:
  #eureka-server
  eureka-server:
    image: ahmedbaz/eureka-server:1.2.0
    restart: always
    ports:
      - '8761:8761'
    networks:
      - currency-network
  #config-server
  config-server:
    depends_on:
      - eureka-server
    image: ahmedbaz/config-server:1.2.0
    restart: always
    ports:
      - '8888:8888'
    environment:
        SPRING.BOOT.ADMIN.CLIENT.URL: http://admin-server:9090
    networks:
      - currency-network    
  #zipkin
  zipkin:
    image: openzipkin/zipkin:2.23
    restart: always
    ports:
      - '9411:9411'
    networks:
      - currency-network
  #gateway-server
  api-gateway:
    depends_on:
      - eureka-server
      - admin-server
    image: ahmedbaz/api-gateway:1.2.0
    restart: always
    ports:
      - '8765:8765'
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin:9411/
      SPRING.BOOT.ADMIN.CLIENT.URL: http://admin-server:9090
    networks:
      - currency-network
  #redis
  redis:
    image: redis:alpine3.17
    restart: always
    ports:
      - '6379:6379'
    networks:
      - currency-network
  #currency-exchange-service
  currency-exchange-service:
    depends_on:
      - redis
      - eureka-server
      - admin-server
    image: ahmedbaz/currency-exchange-service:1.2.0
    restart: always
    ports:
      - '8000:8000'
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.REDIS.HOST: redis
      SPRING.REDIS.port: 6379
      SPRING.ZIPKIN.BASE-URL: http://zipkin:9411/
      SPRING.BOOT.ADMIN.CLIENT.URL: http://admin-server:9090
    networks:
      - currency-network
  #currency-conversion-service
  currency-conversion-service:
    depends_on:
      - eureka-server
      - config-server
      - admin-server
    image: ahmedbaz/currency-conversion-service:1.2.0
    restart: always
    ports:
      - '8100:8100'
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING.ZIPKIN.BASE-URL: http://zipkin:9411/
      SPRING.BOOT.ADMIN.CLIENT.URL: http://admin-server:9090
    networks:
      - currency-network
  #admin-server
  admin-server:
    depends_on:
      - eureka-server
    image: ahmedbaz/admin-server:1.2.0
    ports:
      - '9090:9090'
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
    networks:
      - currency-network

networks:
  currency-network:

